# Statistical Analysis
##  Regression
### Linear regression on  groups

```{r include=FALSE}
library(Hmisc) #impute values
library(naniar) # deal with NAs
library(geosphere)
library(tidyverse) # data handling and viz
library(janitor) #dataframe import cleaning
library(knitr) #nice html tables
library(kableExtra) # nicer knitr tables
library(broom)
library(readr) # load csv stored data
library(geosphere) # for calc daylength
library(effectsize)
```

## Linear Regression
```{r}
kable(mtcars %>%  group_by(as.factor(gear)) %>%
summarise(mean = mean(qsec), sd = sd(qsec))) %>%
  kable_styling(full_width = F) %>%
  kable_minimal()

#Run the same linear regression model by group levels? 
#Instead of running #summary(lm(y~x)) for the number of levels 
#you have, you can use the R package “broom” along with dplyr.

# Run the same regression model for gears ##
kable(mtcars%>% group_by(gear) %>%
  do(fitgear = glance(lm(hp~qsec, data = .))) %>% 
  unnest(fitgear),digits=2) %>%   kable_styling(full_width = F) %>% 
  kable_minimal()
```
[Reference](https://stackoverflow.com/questions/22713325/fitting-several-regression-models-with-dplyr)

```{r}
fit <- lm(qsec ~ wt + hp+disp+factor(cyl), data = mtcars)
summary(fit)
effectsize(fit)
anova_table <- anova(fit)
effectsize(anova_table)


```



## Logistic Regression
### Create the LogR model
```{r}

```

## Principle Component Analysis

### Extracting 1st component

*complete dataset needed for following* 
```{r}

```





## Survival Analysis and Visualisation
### To be completed

## Receiver Operated Curves (ROC)
### To be completed


